# Generated by Django 3.1.12 on 2021-07-13 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20210711_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcard',
            name='startcard',
            field=models.BooleanField(default=False),
        ),
    ]
