# Generated by Django 3.1.12 on 2021-07-14 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcard',
            name='easy',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='flashcard',
            name='hard',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='flashcard',
            name='medium',
            field=models.IntegerField(default=0),
        ),
    ]
