# Generated by Django 3.1.12 on 2021-07-14 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_auto_20210714_2129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flashcard',
            name='easy',
        ),
        migrations.RemoveField(
            model_name='flashcard',
            name='hard',
        ),
        migrations.RemoveField(
            model_name='flashcard',
            name='medium',
        ),
        migrations.AddField(
            model_name='flashcard',
            name='attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='flashcard',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
