# Generated by Django 3.2.3 on 2021-07-15 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_alter_task_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='progress',
            name='color',
            field=models.CharField(default='#ffffff', max_length=7),
        ),
    ]
