# Generated by Django 3.1.12 on 2021-07-14 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_auto_20210714_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashcard',
            name='score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
