# Generated by Django 3.1.12 on 2021-07-14 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_auto_20210714_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
