# Generated by Django 3.2.3 on 2021-07-15 22:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_progress_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progress',
            name='color',
            field=models.CharField(blank=True, default='#ffffff', max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='progress',
            name='percent',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
