# Generated by Django 3.1.12 on 2021-07-18 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_pomodoro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pomodoro',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
