# Generated by Django 3.1.12 on 2021-07-18 14:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0012_auto_20210718_1411'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pomodoro',
            name='count',
        ),
        migrations.AlterField(
            model_name='pomodoro',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pomodoro',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pomodoro', to=settings.AUTH_USER_MODEL),
        ),
    ]
